### ISSUE TITLE
Assignment 01 -- Platform preparation

### ISSUE THREAD

**Issue by dudung** [dudung/sk5010-01-2024-1#1]
+ Check your today present on [SIX](https://six.itb.ac.id/) (30 mins)
+ Create [GitHub](https://github.com/) account and report your link to your user profile (30 mins), <br>e.g. https://github.com/dudung.
+ Create [account](https://medium.com/) and report link to user profile (30 mins), <br>e.g. https://medium.com/@6unpnp.
+ Create [OSF](https://osf.io/) account and report link to user profile (30 mins), <br>e.g. https://osf.io/pkc6z/.
+ Create a story on Medium about motivation why you want to take this course and what knowledge you would like to have by taking this course in a 10-minutes story and provide the link to the story here (4 hours).

**Comment by ilonajoan07** [comment]
Ilona Joan Manuela (20924008)

https://github.com/ilonajoan07
https://medium.com/@ilona.10520059
https://osf.io/xpa2c
https://medium.com/@ilona.10520059/visualisation-in-science-a-computational-science-course-84dab43ba4f2

**Comment by kahfirk** [comment]
1st Assignment SK5010 
Kahfi Rizky Kosasih, NIM: 20924006 

Github Account:
https://github.com/kahfirk

Medium Account:
https://medium.com/@kahfirk15

OSF Account:
https://osf.io/bxjcn

Medium Article:
https://medium.com/@kahfirk15/my-thoughts-on-visualization-science-967bbf542d9d

**Comment by gerendc** [comment]
1st Assignment SK5010
Name: Gerend Christopher
NIM: 20924009

Github Account:
https://github.com/gerendc

Medium Account: 
https://medium.com/@gerendc

OSF Account:
osf.io/ts6vn

Medium Article:
https://medium.com/@gerendc/enrolling-visualization-in-science-course-71a895b269b7

**Comment by ariansyahedu** [comment]
1st Assignment SK5010
Name: Ariansyah
NIM: 20924007

Github Account:
https://github.com/ariansyahedu

Medium Account:
https://medium.com/@ariansyahedu

OSF Account:
https://osf.io/nd42z/

Medium Article:
https://medium.com/@ariansyahedu/reasons-that-laid-the-foundation-for-me-to-learn-visualization-in-science-3d58cfa9f86e

**Comment by MarcoSutisna** [comment]
Tugas 1 
Nama : Marco Sutisna Putra
NIM : 20924001

Link GitHub : https://github.com/MarcoSutisna
Link Medium : https://medium.com/@marcosutisna
Link OSF : [osf.io/p2wvs](https://osf.io/p2wvs/)
Link Article Medium : https://medium.com/@marcosutisna/motivasi-mengikuti-kelas-visualisasi-dalam-sains-sebagai-mahasiswa-pasca-sarjana-itb-jurusan-sains-78e33a24ff76

untuk present kehadiran saya belum bisa karena belum terdaftar saat pemilihan rencana studi, namun akan daftar saat PRS. Terima kasih

**Comment by arvincans** [comment]
Tugas 1
Nama : Arvin Cansius
NIM : 20924003

Github : https://github.com/arvincans
Medium : https://medium.com/@arvincansius
OSF : https://osf.io/8myaf/
Medium Article : https://medium.com/@arvincansius/my-motivation-why-i-want-to-take-visualization-in-science-course-717eb021bb2f

**Comment by borousama** [comment]
First Assignment of SK5010
Ahmad Zaini Zahrandika
20923302

Github: https://github.com/borousama
Medium: https://medium.com/@izay2001
OSF: https://osf.io/3rbdv/

Medium article: https://medium.com/@izay2001/why-i-want-to-take-visualization-in-science-course-66aa2c5a5e30

**Comment by azainiz** [comment]
First Assignment of SK5010
Ahmad Zaini Zahrandika
20923302

Github: https://github.com/azainiz
Medium: https://medium.com/@izay2001
OSF: https://osf.io/3rbdv/

Medium article: https://medium.com/@izay2001/why-i-want-to-take-visualization-in-science-course-66aa2c5a5e30

**Comment by dudung** [comment]
## 11-sep-2024
![image](https://github.com/user-attachments/assets/644e7245-3c60-40b8-9800-76f33723b844)

## 13-sep-2024
1. https://github.com/ilonajoan07
2. https://github.com/kahfirk
3. https://github.com/gerendc
4. https://github.com/ariansyahedu
5. https://github.com/MarcoSutisna
6. https://github.com/arvincans
7. https://github.com/azainiz
