### ISSUE TITLE
Assignment 02 -- Course introduction and RBL topics

### ISSUE THREAD

**Issue by dudung** [dudung/sk5010-01-2024-1#2]
## learning outcome
1. Students are able to analyze data from various phenomena in science using graphic tools and visualization techniques to understand science quantitatively and qualitatively.
2. Students are able to produce scientific articles that can be submitted to proceedings or journals, both national and international.

## activities
1. Discussion about History of scientific development and visualization of various scientific phenomena, as well as various software and frameworks, as well as platforms that can be used.
2. Introduction to various visualization techniques in explaining data, processes, natural phenomena, hypotheses, and other things that cannot be conveyed only by writing and formulas.
4. Searching for data and creating visualizations uses programming languages, software, frameworks, or online platforms to make it easier to analyze and explain phenomena in the world of science.
5. Performing research-based learning (RBL), which is carried out independently by each student based on each **student's choice of topics that have been selected at the beginning of the lecture meeting**.
6. Preparation of scientific articles by each student from the results of research-based learning that has been carried out by each student
7. Presentation of final reports from each student and submission of scientific articles that have been written by each student.

## tasks (5 hours)
+ Create a Medium story about some RBL topics you are interested to carry for this course.
+ Suggest, in the story, programming language, software, platform, etc supporting each topics you choose.
+ Write also prediction of time required to finish each topics.
+ Inform your student ID and link to the story here.

**Comment by MarcoSutisna** [comment]
Marco Sutisna Putra
NIM: 20924001

berikut ini link artikel medium saya terkait RBL Topic yang akan saya ambil: https://medium.com/@marcosutisna/mendeteksi-kandungan-gizi-makanan-menggunakan-optical-character-recognition-a12f4ad18978

**Comment by kahfirk** [comment]
Kahfi Rizky Kosasih 
NIM: 20924006

Medium Article: 
https://medium.com/@kahfirk15/visualization-in-science-research-based-learning-topic-8888d3c4f065

**Comment by arvincans** [comment]
Name : Arvin Cansius
NIM : 20924003

medium story : https://medium.com/@arvincansius/rbl-research-based-learning-topics-im-interested-for-visualisation-in-science-course-1138cfb4ff8f

**Comment by ilonajoan07** [comment]
Ilona Joan Manuela (20924008)

https://medium.com/@ilona.10520059/research-based-learning-topics-on-mind-6c50ba61613d

**Comment by gerendc** [comment]
Gerend Christopher (20924009)
https://medium.com/@gerendc/visualization-in-science-research-based-learning-topics-a72fd8bdc303

**Comment by azainiz** [comment]
Ahmad Zaini Zahrandika (20923302)

Medium story: https://medium.com/@izay2001/research-based-learning-topics-f3bbac93e828

**Comment by ariansyahedu** [comment]
Ariansyah (20924007)

https://medium.com/@ariansyahedu/potential-topics-for-research-based-learning-in-visualization-in-science-ed04bec1b1c5

**Comment by dudung** [comment]
## 18-sep-2024
![sk5010-01-2024-1-20240918](https://github.com/user-attachments/assets/7bcdb657-9341-46ba-b442-5e7c8559758f)
